# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-12-01 15:33+0600\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: .\venv\Lib\site-packages\social_auth\backends\pipeline\social.py:17
#, python-format
msgid "This %(provider)s account is already in use."
msgstr ""

#: .\venv\Lib\site-packages\social_auth\exceptions.py:10
#, python-format
msgid "Backend error: %s"
msgstr ""

#: .\venv\Lib\site-packages\social_auth\exceptions.py:17
#, python-format
msgid "Incorrect authentication service \"%s\""
msgstr ""

#: .\venv\Lib\site-packages\social_auth\exceptions.py:31
msgid "Stop pipeline"
msgstr ""

#: .\venv\Lib\site-packages\social_auth\exceptions.py:45
msgid "Authentication process was cancelled"
msgstr ""

#: .\venv\Lib\site-packages\social_auth\exceptions.py:47
#, python-format
msgid "Authentication failed: %s"
msgstr ""

#: .\venv\Lib\site-packages\social_auth\exceptions.py:54
msgid "Authentication process canceled"
msgstr ""

#: .\venv\Lib\site-packages\social_auth\exceptions.py:68
#, python-format
msgid "Token error: %s"
msgstr ""

#: .\venv\Lib\site-packages\social_auth\exceptions.py:78
#, python-format
msgid "Missing needed parameter %s"
msgstr ""

#: .\venv\Lib\site-packages\social_auth\exceptions.py:84
msgid "Session value state missing."
msgstr ""

#: .\venv\Lib\site-packages\social_auth\exceptions.py:90
msgid "Wrong state parameter given."
msgstr ""

#: .\venv\Lib\site-packages\social_auth\exceptions.py:101
msgid "User revoke access to the token"
msgstr ""
